CajaBundle_caja:
    resource: "@SistemaCajaBundle/Resources/config/routing/caja.yml"
    prefix:   /caja

SistemaCajaBundle_codigobarra:
    resource: "@SistemaCajaBundle/Resources/config/routing/codigobarra.yml"
    prefix:   /codigobarra

SistemaCajaBundle_apertura:
    resource: "@SistemaCajaBundle/Resources/config/routing/apertura.yml"
    prefix:   /apertura

SistemaCajaBundle_registro:
    resource: "@SistemaCajaBundle/Resources/config/routing/registro.yml"
    prefix:   /registro

SistemaCajaBundle_tipopago:
    resource: "@SistemaCajaBundle/Resources/config/routing/tipopago.yml"
    prefix:   /tipopago

SistemaCajaBundle_diego:
    resource: "@SistemaCajaBundle/Resources/config/routing/diego.yml"
    prefix:   /diego
