CajaBundle_caja:
    resource: "@SistemaCajaBundle/Resources/config/routing/caja.yml"
    prefix:   /caja

SistemaCajaBundle_codigobarra:
    resource: "@SistemaCajaBundle/Resources/config/routing/codigobarra.yml"
    prefix:   /codigobarra

SistemaCajaBundle_apertura:
    resource: "@SistemaCajaBundle/Resources/config/routing/apertura.yml"
    prefix:   /apertura

SistemaCajaBundle_registro:
    resource: "@SistemaCajaBundle/Resources/config/routing/registro.yml"
    prefix:   /registro

SistemaCajaBundle_tipopago:
    resource: "@SistemaCajaBundle/Resources/config/routing/tipopago.yml"
    prefix:   /tipopago

SistemaCajaBundle_feriado:
    resource: "@SistemaCajaBundle/Resources/config/routing/feriado.yml"
    prefix:   /feriado

SistemaCajaBundle_responsable:
    resource: "@SistemaCajaBundle/Resources/config/routing/responsable.yml"
    prefix:   /responsable

SistemaCajaBundle_puesto:
    resource: "@SistemaCajaBundle/Resources/config/routing/puesto.yml"
    prefix:   /puesto

SistemaCajaBundle_delegacion:
    resource: "@SistemaCajaBundle/Resources/config/routing/delegacion.yml"
    prefix:   /delegacion

SistemaCajaBundle_habilitacion:
    resource: "@SistemaCajaBundle/Resources/config/routing/habilitacion.yml"
    prefix:   /habilitacion