CajaBundle_caja:
    resource: "@SistemaCajaBundle/Resources/config/routing/caja.yml"
    prefix:   /caja

SistemaCajaBundle_codigobarra:
    resource: "@SistemaCajaBundle/Resources/config/routing/codigobarra.yml"
    prefix:   /codigobarra

SistemaCajaBundle_apertura:
    resource: "@SistemaCajaBundle/Resources/config/routing/apertura.yml"
    prefix:   /apertura