parameters:
    caja.listener.class: Caja\SistemaCajaBundle\Listener\CajaListener

services:
#    caja.example:
#        class: %caja.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    caja.entity.listener:
        class: %caja.listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad}

    caja_login_listener:
        class: %caja.listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }


