parameters:
    caja.listener.class: Caja\SistemaCajaBundle\Listener\CajaListener
    caja.cajamanager:    Caja\SistemaCajaBundle\Lib\CajaManager
    caja.barra:          Caja\SistemaCajaBundle\Lib\CodigoBarraLive
    comercio.manager:    Caja\ComercioBundle\Entity\Comercio

services:
    caja.entity.listener:
        class: %caja.listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad}

    caja_login_listener:
        class: %caja.listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }

    sistemacaja.caja_manager:
        class: %caja.cajamanager%
        arguments: [@service_container]

    sistemacaja.codigobarra:
        class: %caja.barra%
        arguments: [@service_container, @lar.parametro.tabla,@logger]

    sistemacaja.ticket:
        class:  Caja\SistemaCajaBundle\Lib\Ticket
        arguments: [@caja.manager]

    caja.manager:
        alias:  sistemacaja.caja_manager
        arguments: [@service_container]

    caja.barra:
        alias: sistemacaja.codigobarra

    twig.extension.caja.manager:
        class:  Caja\SistemaCajaBundle\Twig\Extension\CajaExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension}

    sistemacaja.prorroga:
        class: 'Caja\SistemaCajaBundle\Lib\ProrrogaService'
        arguments: [@doctrine.orm.entity_manager]

    caja.oracleInit:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }