parameters:
    caja.listener.class: Caja\SistemaCajaBundle\Listener\CajaListener
    caja.cajamanager:    Caja\SistemaCajaBundle\Lib\CajaManager
    caja.barra:          Caja\SistemaCajaBundle\Lib\CodigoBarraLive
    caja.ticket:         Caja\SistemaCajaBundle\Lib\Ticket

services:
#    caja.example:
#        class: %caja.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    caja.entity.listener:
        class: %caja.listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad}

    caja_login_listener:
        class: %caja.listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }

    sistemacaja.caja_manager:
        class: %caja.cajamanager%
        arguments: [@service_container]

    sistemacaja.codigobarra:
        class: %caja.barra%
        arguments: [@doctrine.orm.entity_manager, @lar.parametro.tabla,@logger]

    sistemacaja.ticket:
        class:  %caja.ticket%
        arguments: [@caja.manager]

    caja.manager:
        alias:  sistemacaja.caja_manager

    caja.barra:
        alias: sistemacaja.codigobarra

    twig.extension.caja.manager:
        class:  Caja\SistemaCajaBundle\Twig\Extension\CajaExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension}

    caja.oracleInit:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }