parameters:
#    comercio.example.class: Caja\ComercioBundle\Example

services:
#    comercio.example:
#        class: %comercio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
