imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines:         ['twig']  #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
#            - 'MopaBootstrapBundle:Form:fields.html.twig'
#            - LarParametroBundle:Form:fields.html.twig
#            - LarUtilsBundle:Form:fields.html.twig
            - LexikFormFilterBundle:Form:form_div_layout.html.twig
    globals:
        usuario_imagenes: 'uploads/users/'
        lar:
            nombre_sistema: 'Sistema de Cajas'
            logo_empresa:  'img/logo-posadas_bco.png'
            usuario:
                imagenes: 'uploads/users/'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "UTF8"
        #charset:    "AL32UTF8"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    navbar: ~
    form:
#        templating: false
        render_fieldset: false
        show_legend: false # default is true
        show_child_legend: true # default is true
        render_required_asterisk: false
        error_type: block # or inline which is default
        render_optional_text: false


        collection:
            widget_remove_btn:
                icon: trash
                icon_color: white
            widget_add_btn:
                icon: plus-sign


white_october_breadcrumbs: ~

lar_utils:
    token: "lartok1589452221"
    options:
        swf:  'dify/uploadify.swf'

khepin_yaml_fixtures:
    resources:
        - SistemaCajaBundle
        - LarParametroBundle

parameters:
    lar.usuario.imagenes: %kernel.root_dir%/../web/uploads/users/
    caja.apertura.dir_files: %kernel.root_dir%/../envios/



lar_parametro:
    tabla_agregable: true

avalanche_imagine:
    source_root: C:/Vertrigo\www
    #source_root: %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web

    cache_prefix: media/cache
    driver:       gd
    filters:      []


    filters:
        foto_login:
            type:    thumbnail
            options: { size: [50,50], mode: outbound }
        foto_usuario:
            type:    thumbnail
            options: { size: [250,250], mode: outbound }