imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
#    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            #- 'MopaBootstrapBundle:Form:fields.html.twig'
            - LexikFormFilterBundle:Form:form_div_layout.html.twig
            - ParametroBundle:Form:fields.html.twig
            - LarUtilsBundle:Form:fields.html.twig
    globals:
        usuario_imagenes: 'uploads/users/'
        lar:
            nombre_sistema: 'Sistema de Cajas'
            logo_empresa:  'img/logo-posadas_bco.png'
            usuario:
                imagenes: 'uploads/users/'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    navbar: ~
    form:
#        templating: false
        render_fieldset: false
        show_legend: false # default is true
        show_child_legend: true # default is true
        render_required_asterisk: false
        error_type: block # or inline which is default
        render_optional_text: false


        collection:
            widget_remove_btn:
                icon: trash
                icon_color: white
            widget_add_btn:
                icon: plus-sign


white_october_breadcrumbs: ~

lar_utils:
    token: "lartok1589452221"
    options:
        swf:  'dify/uploadify.swf'

khepin_yaml_fixtures:
    resources:
        - SistemaCajaBundle
        - ParametroBundle

parameters:
    lar.usuario.imagenes: %kernel.root_dir%/../web/uploads/users/