common_auditor:
    resource: "@CommonAuditorBundle/Resources/config/routing.yml"
    prefix:   /

caja:
    resource: "@SistemaCajaBundle/Resources/config/routing.yml"
    prefix:   /

lar_parametro:
    resource: "@LarParametroBundle/Resources/config/routing.yml"
    prefix:   /

lar_utils:
    resource: "@LarUtilsBundle/Resources/config/routing.yml"
    prefix:   /

Usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

upload_file:
    pattern:  /upload
    defaults: { _controller: PortadaBundle:Default:uploadFile }

home_page:
    pattern: /
    defaults: { _controller: UsuarioBundle:Usuario:index }

_imagine:
    resource: .
    type:     imagine

pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: SistemaCajaBundle:Sitio:estatica }
# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
