jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
#        frontend_cliente:
#            pattern: ^/*
#            anonymous: ~
##            provider: clientes
#            form_login:
#                use_referer: true
#                login_path: /login
#                check_path: /login_check
#                default_target_path: home_page
#                always_use_default_target_path: true
#
#            logout:
#                path: /logout

        frontend_otro:
            pattern: ^/*
            anonymous: ~
            provider: usuarios
            form_login:
                use_referer: true
                login_path: /login
                check_path: /login_check
                default_target_path: home_page
                always_use_default_target_path: true

            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/usuario/*, role: ROLE_ADMIN }
        - { path: ^/larutils/*, role: ROLE_USUARIO }


        - { path: ^/*, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }


    providers:
#        all_provider:
#            chain:
#                providers: ["usuarios", "clientes"]
        usuarios:
            entity: { class: Lar\UsuarioBundle\Entity\Usuario,  property:    email }
#        clientes:
#            entity: { class: Stock\StockBundle\Entity\Cliente,    property:    usuario }



    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Lar\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        #Stock\StockBundle\Entity\Cliente:   { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USUARIO, ROLE_ADMIN, ROLE_CLIENTE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PROV_ADMIN:  [ROLE_CLIENTE, ROLE_USUARIO]
