usuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

grupo:
    resource: "@UsuarioBundle/Resources/config/routing/grupo.yml"
    prefix:   /grupo

seguridad:
    resource: "@UsuarioBundle/Resources/config/routing/seguridad.yml"
    prefix:   /

perfil:
    resource: "@UsuarioBundle/Resources/config/routing/perfil.yml"
    prefix:   /perfil

usuarioingreso:
    resource: "@UsuarioBundle/Resources/config/routing/usuarioingreso.yml"
    prefix:   /usuarioingreso
