parameters:
#    usuario.example.class: Lar\UsuarioBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    Usuario.listener:
        class: Lar\UsuarioBundle\Listener\UsuarioUpdater
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

