parameters:
#    usuario.example.class: Lar\UsuarioBundle\Example

services:

    usuario_manager:
        class: Lar\UsuarioBundle\Listener\UsuarioManager
        arguments: [@service_container]

    login_listener:
       class: Lar\UsuarioBundle\Listener\LoginListener
       arguments: [@service_container]
       tags:
          - { name: kernel.event_listener, event: security.interactive_login}

    Usuario.listener:
        class: Lar\UsuarioBundle\Listener\UsuarioUpdater
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

