parameters:
#    usuario.example.class: Lar\UsuarioBundle\Example

services:
    login_listener:
       class: Lar\UsuarioBundle\Listener\LoginListener
       tags:
          - { name: kernel.event_listener, event: security.interactive_login }

    Usuario.listener:
        class: Lar\UsuarioBundle\Listener\UsuarioUpdater
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

