apertura:
    pattern:  /
    defaults: { _controller: "SistemaCajaBundle:Apertura:index" }

apertura_show:
    pattern:  /{id}/show
    defaults: { _controller: "SistemaCajaBundle:Apertura:show" }

apertura_new:
    pattern:  /new
    defaults: { _controller: "SistemaCajaBundle:Apertura:new" }

apertura_create:
    pattern:  /create
    defaults: { _controller: "SistemaCajaBundle:Apertura:create" }
    requirements: { _method: post }

apertura_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SistemaCajaBundle:Apertura:edit" }

apertura_update:
    pattern:  /{id}/update
    defaults: { _controller: "SistemaCajaBundle:Apertura:update" }
    requirements: { _method: post }

apertura_cierre:
    pattern:  /cierre
    defaults: { _controller: "SistemaCajaBundle:Apertura:cierre" }
    #requirements: { _method: post }

apertura_envio_mail:
    pattern:  /envioMail
    defaults: { _controller: "SistemaCajaBundle:Apertura:envioMail" }
    #requirements: { _method: post }

apertura_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SistemaCajaBundle:Apertura:delete" }
    requirements: { _method: post }

apertura_monitor:
    pattern: /monitor
    defaults: { _controller: "SistemaCajaBundle:Apertura:monitor" }

apertura_anulado:
    pattern: /anular
    defaults: { _controller: "SistemaCajaBundle:Apertura:anular" }

anulacion_comprobante:
    pattern: /registrarAnulacion
    defaults: { _controller: "SistemaCajaBundle:Apertura:anularComprobante" }

apertura_existe_comprobante:
      pattern:  /barra
      defaults: { _controller: "SistemaCajaBundle:Apertura:existeComprobante" }

apertura_sock:
      pattern:  /sock
      defaults: { _controller: "SistemaCajaBundle:Apertura:sock" }

apertura_preparar_envio:
    pattern:  /{id}/prepararEnvio
    defaults: { _controller: "SistemaCajaBundle:Apertura:prepararEnvio" }

apertura_enviar_mail:
    pattern:  /{id}/enviarMail
    defaults: { _controller: "SistemaCajaBundle:Apertura:enviarMail" }

apertura_preparar_reimpresion_cierre:
    pattern:  /{id}/prepararReimpresionCierre
    defaults: { _controller: "SistemaCajaBundle:Apertura:prepararReimpresionCierre" }

apertura_preparar_reimpresion_cierre_reporte:
    pattern:  /{id}/prepararReimpresionCierreReporte
    defaults: { _controller: "SistemaCajaBundle:Apertura:prepararReimpresionCierreReporte" }

apertura_reimprimir_cierre:
    pattern:  /{id}/reimprimirCierre
    defaults: { _controller: "SistemaCajaBundle:Apertura:reimprimirCierre" }

apertura_mostrar_reimpresion_tickets:
    #en esta ventana se ven los tickets cobrados en la caja actual
    pattern:  /{id}/mostrarReimpresionTickets
    defaults: { _controller: "SistemaCajaBundle:Apertura:mostrarReimpresionTickets" }

apertura_preparar_reimpresion_ticket:
    #en esta ventana se ven los datos del ticket seleccionado en la ventana anterior
    pattern:  /{id}/prepararReimpresionTicket
    defaults: { _controller: "SistemaCajaBundle:Apertura:prepararReimpresionTicket" }

apertura_reimprimir_ticket:
    #en esta accion recien se reimprime el ticket
    pattern:  /{id}/reimprimirTicket
    defaults: { _controller: "SistemaCajaBundle:Apertura:reimprimirTicket" }

apertura_mas_info:
    #Es llamada desde el monitor para ver el detalle de cobros de un tipo de seccion
    pattern:  /masInfo
    defaults: { _controller: "SistemaCajaBundle:Apertura:masInfo" }