barradetalle:
    pattern:  /
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:index" }

barradetalle_show:
    pattern:  /{id}/show
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:show" }

barradetalle_new:
    pattern:  /new
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:new" }

barradetalle_create:
    pattern:  /create
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:create" }
    requirements: { _method: post }

barradetalle_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:edit" }

barradetalle_update:
    pattern:  /{id}/update
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:update" }
    requirements: { _method: post }

barradetalle_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SistemaCajaBundle:BarraDetalle:delete" }
    requirements: { _method: post }
