diego:
    pattern:  /
    defaults: { _controller: "SistemaCajaBundle:Diego:index" }

diego_show:
    pattern:  /{id}/show
    defaults: { _controller: "SistemaCajaBundle:Diego:show" }

diego_new:
    pattern:  /new
    defaults: { _controller: "SistemaCajaBundle:Diego:new" }

diego_create:
    pattern:  /create
    defaults: { _controller: "SistemaCajaBundle:Diego:create" }
    requirements: { _method: post }

diego_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SistemaCajaBundle:Diego:edit" }

diego_update:
    pattern:  /{id}/update
    defaults: { _controller: "SistemaCajaBundle:Diego:update" }
    requirements: { _method: post }

diego_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SistemaCajaBundle:Diego:delete" }
    requirements: { _method: post }
