registro:
    pattern:  /
    defaults: { _controller: "SistemaCajaBundle:Registro:registro" }

registro_create:
    pattern:  /create
    defaults: { _controller: "SistemaCajaBundle:Registro:create" }

registro_barra:
      pattern:  /barra
      defaults: { _controller: "SistemaCajaBundle:Registro:barraDetalle" }


registro_ticket:
      pattern:  /{tipo}/ticket
      defaults: { _controller: "SistemaCajaBundle:Registro:getTicket" }