<?php

namespace Caja\SistemaCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * CajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaRepository extends EntityRepository
{
    public function findCajas()
    {
        $c = $this->createQueryBuilder('c');
        $c->join("c.cajero","t");

        return $c;
    }
}
