<?php

namespace Caja\SistemaCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Caja\SistemaCajaBundle\Entity\LoteDetalle;
/**
 * LoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteRepository extends EntityRepository
{
    /**
     * A partir de un numero de comprobante, se recuperan los comprobantes
     *pertenecientes al lote correspondiente, que no esten anulados
     * @param $codigo_barra
     * @return mixed
     */
    public function getLote($apertura_id, $codigo_barra)
    {
        $em = $this->getEntityManager();
        $q = $em->createQuery("
              SELECT ld
              FROM
                  SistemaCajaBundle:LoteDetalle ld JOIN ld.lote l
              WHERE
                  ld.codigo_barra = :codigo_barra
                  and l.apertura = :apertura_id
                  and ld.anulado = 0
              ");
        $q->setParameter('codigo_barra', $codigo_barra);
        $q->setParameter('apertura_id', $apertura_id);

        try {
            $res = $q->getSingleResult();
            return $res->getLote();
        } catch (\Doctrine\Orm\NoResultException $e) {
            //No trajo resultados:
            return null;
        }  catch (\Doctrine\Orm\NonUniqueResultException $e) {
            //Si devolvio una excepcion es porque trajo mas de un resultado,
            // o sea es un error grave haber cobrado mas de una vez un comprobante
            return null;
        }
    }
}