<?php

namespace Caja\SistemaCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableRepository extends EntityRepository
{
    public function getResponsablesActivos(){
        $em = $this->getEntityManager();
        $activo = true;
        $consulta = $em->createQuery("
              SELECT r
              FROM
                  SistemaCajaBundle:Responsable r
              WHERE
                  r.activo = :activo
              ")
            ->setParameter('activo', $activo)
        ;

        return $consulta->getResult();
    }
}
