<?php

namespace Caja\SistemaCajaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TipoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPagoRepository extends EntityRepository
{
    public function getDefaulPago(){

        $em = $this->getEntityManager();
        $q = $em->createQuery('
        	SELECT t
              FROM SistemaCajaBundle:TipoPago t
             WHERE t.divisible = 1');
        try{
            $res = $q->getSingleResult();
        }catch(NoResultException $e){
            throw($e);
        }

        return $res->getId();

    }

    /**
     * Devuelve el tipo de pago Divisible
     * @return object
     */
    public function getTipoPagoDivisible($tipo_pago_divisible){
        $em = $this->getEntityManager();

        $tipo_pago = $this->findOneBy(array('divisible' => $tipo_pago_divisible));

        return $tipo_pago;
        /*$tipo_pago = $em->getRepository('SistemaCajaBundle:TipoPago') ->findOneBy(array(
            'divisible' => $tipo_pago_divisible
        ));*/

    }
}
